PROJECT_DIR=.
ARDMK_DIR=$(PROJECT_DIR)/../Arduino-Makefile

USER_LIB_PATH=$(realpath $(PROJECT_DIR)/../lib)

BOARD_TAG=mega
BOARD_SUB=atmega2560
MONITOR_PORT=/dev/ttyACM0

OBJDIR=$(PROJECT_DIR)/../bin/$(BOARD_TAG)

include $(ARDMK_DIR)/Arduino.mk
